# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1745, 1264)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_digito8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito8.setObjectName("button_digito8")
        self.gridLayout_3.addWidget(self.button_digito8, 1, 1, 1, 1)
        self.button_digito3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito3.setObjectName("button_digito3")
        self.gridLayout_3.addWidget(self.button_digito3, 3, 0, 1, 1)
        self.button_digito9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito9.setObjectName("button_digito9")
        self.gridLayout_3.addWidget(self.button_digito9, 1, 0, 1, 1)
        self.button_div = QtWidgets.QPushButton(self.centralwidget)
        self.button_div.setObjectName("button_div")
        self.gridLayout_3.addWidget(self.button_div, 4, 3, 1, 1)
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.resultado.setFont(font)
        self.resultado.setText("")
        self.resultado.setObjectName("resultado")
        self.gridLayout_3.addWidget(self.resultado, 0, 1, 1, 1)
        self.button_digito2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito2.setObjectName("button_digito2")
        self.gridLayout_3.addWidget(self.button_digito2, 3, 1, 1, 1)
        self.button_digito1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito1.setObjectName("button_digito1")
        self.gridLayout_3.addWidget(self.button_digito1, 3, 2, 1, 1)
        self.button_digito4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito4.setObjectName("button_digito4")
        self.gridLayout_3.addWidget(self.button_digito4, 2, 2, 1, 1)
        self.button_digito6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito6.setObjectName("button_digito6")
        self.gridLayout_3.addWidget(self.button_digito6, 2, 0, 1, 1)
        self.button_digito0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito0.setObjectName("button_digito0")
        self.gridLayout_3.addWidget(self.button_digito0, 4, 0, 1, 1)
        self.resultado_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.resultado_2.setFont(font)
        self.resultado_2.setStyleSheet("color: rgb(96, 1, 103);")
        self.resultado_2.setText("")
        self.resultado_2.setObjectName("resultado_2")
        self.gridLayout_3.addWidget(self.resultado_2, 0, 0, 1, 1)
        self.button_soma = QtWidgets.QPushButton(self.centralwidget)
        self.button_soma.setObjectName("button_soma")
        self.gridLayout_3.addWidget(self.button_soma, 1, 3, 1, 1)
        self.button_digito7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito7.setObjectName("button_digito7")
        self.gridLayout_3.addWidget(self.button_digito7, 1, 2, 1, 1)
        self.button_digito5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_digito5.setObjectName("button_digito5")
        self.gridLayout_3.addWidget(self.button_digito5, 2, 1, 1, 1)
        self.button_digitodot = QtWidgets.QPushButton(self.centralwidget)
        self.button_digitodot.setObjectName("button_digitodot")
        self.gridLayout_3.addWidget(self.button_digitodot, 4, 1, 1, 1)
        self.button_sub = QtWidgets.QPushButton(self.centralwidget)
        self.button_sub.setObjectName("button_sub")
        self.gridLayout_3.addWidget(self.button_sub, 2, 3, 1, 1)
        self.button_mul = QtWidgets.QPushButton(self.centralwidget)
        self.button_mul.setObjectName("button_mul")
        self.gridLayout_3.addWidget(self.button_mul, 3, 3, 1, 1)
        self.button_equals = QtWidgets.QPushButton(self.centralwidget)
        self.button_equals.setObjectName("button_equals")
        self.gridLayout_3.addWidget(self.button_equals, 4, 2, 1, 1)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear.sizePolicy().hasHeightForWidth())
        self.button_clear.setSizePolicy(sizePolicy)
        self.button_clear.setObjectName("button_clear")
        self.gridLayout_3.addWidget(self.button_clear, 0, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.button_digito6.pressed.connect(MainWindow.digito6) # type: ignore
        self.button_div.pressed.connect(MainWindow.div) # type: ignore
        self.button_digitodot.pressed.connect(MainWindow.digitodot) # type: ignore
        self.button_sub.pressed.connect(MainWindow.sub) # type: ignore
        self.button_digito3.pressed.connect(MainWindow.digito3) # type: ignore
        self.button_digito5.pressed.connect(MainWindow.digito5) # type: ignore
        self.button_digito7.pressed.connect(MainWindow.digito7) # type: ignore
        self.button_digito1.pressed.connect(MainWindow.digito1) # type: ignore
        self.button_clear.pressed.connect(MainWindow.clear) # type: ignore
        self.button_digito8.pressed.connect(MainWindow.digito8) # type: ignore
        self.button_digito0.pressed.connect(MainWindow.digito0) # type: ignore
        self.button_digito4.pressed.connect(MainWindow.digito4) # type: ignore
        self.button_mul.pressed.connect(MainWindow.mul) # type: ignore
        self.button_equals.pressed.connect(MainWindow.equals) # type: ignore
        self.button_soma.pressed.connect(MainWindow.sum) # type: ignore
        self.button_digito2.pressed.connect(MainWindow.digito2) # type: ignore
        self.button_digito9.pressed.connect(MainWindow.digito9) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_digito8.setText(_translate("MainWindow", "8"))
        self.button_digito3.setText(_translate("MainWindow", "3"))
        self.button_digito9.setText(_translate("MainWindow", "9"))
        self.button_div.setText(_translate("MainWindow", "/"))
        self.button_digito2.setText(_translate("MainWindow", "2"))
        self.button_digito1.setText(_translate("MainWindow", "1"))
        self.button_digito4.setText(_translate("MainWindow", "4"))
        self.button_digito6.setText(_translate("MainWindow", "6"))
        self.button_digito0.setText(_translate("MainWindow", "0"))
        self.button_soma.setText(_translate("MainWindow", "+"))
        self.button_digito7.setText(_translate("MainWindow", "7"))
        self.button_digito5.setText(_translate("MainWindow", "5"))
        self.button_digitodot.setText(_translate("MainWindow", "."))
        self.button_sub.setText(_translate("MainWindow", "-"))
        self.button_mul.setText(_translate("MainWindow", "x"))
        self.button_equals.setText(_translate("MainWindow", "="))
        self.button_clear.setText(_translate("MainWindow", "CLEAR"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
